# /backend/utils.py
"""Utility functions for Nginx configuration management"""

import os
import subprocess
from config import Config
from models import Location

class NginxConfigGenerator:
    """Generate Nginx configuration files"""
    
    @staticmethod
    def generate_config(domain):
        """Generate complete Nginx configuration for a domain"""
        domain_name = domain['name']
        server_name = domain['server_name']
        listen_port = domain['listen_port']
        
        config = f"""# Generated by Nginx Configerrrrrr
# Domain: {domain_name}

server {{
    listen {listen_port};
    server_name {server_name};
    
    # Logs
    access_log {Config.NGINX_LOG_DIR}/{domain_name}/access.log;
    error_log {Config.NGINX_LOG_DIR}/{domain_name}/error.log;
"""
        
        # Get locations
        locations = Location.get_by_domain(domain['id'])
        
        for location in locations:
            config += NginxConfigGenerator._generate_location_block(location)
        
        config += "}\n"
        
        return config
    
    @staticmethod
    def _generate_location_block(location):
        """Generate a location block"""
        path = location['path']
        modifier = location['match_modifier']
        mode = location['mode']
        
        modifier_str = f" {modifier}" if modifier else ""
        block = f"\n    location{modifier_str} {path} {{\n"
        
        if mode == 'advanced' and location['config_content']:
            # Use advanced custom configuration
            for line in location['config_content'].split('\n'):
                if line.strip():
                    block += f"        {line.strip()}\n"
        else:
            # Generate basic configuration
            forward_type = location['forward_type']
            
            if forward_type == 'dynamic' and location['proxy_pass']:
                proxy_pass = location['proxy_pass']
                block += f"        proxy_pass {proxy_pass};\n"
                block += """        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 1200s;
        proxy_send_timeout 1200s;
        proxy_read_timeout 1200s;
        client_max_body_size 500m;
        client_body_buffer_size 80m;
        keepalive_timeout 300s;
"""
            elif forward_type == 'static' and location['root_path']:
                root_path = location['root_path']
                block += f"        root {root_path};\n"
                block += "        index index.html index.htm;\n"
        
        block += "    }\n"
        
        return block
    
    @staticmethod
    def write_config(domain):
        """Write configuration file to disk"""
        domain_name = domain['name']
        config = NginxConfigGenerator.generate_config(domain)
        
        # Ensure log directory exists
        log_dir = os.path.join(Config.NGINX_LOG_DIR, domain_name)
        os.makedirs(log_dir, exist_ok=True)
        
        # Write config file
        conf_path = os.path.join(Config.NGINX_CONF_DIR, f"{domain_name}.conf")
        with open(conf_path, 'w') as f:
            f.write(config)
        
        return conf_path

class NginxManager:
    """Manage Nginx service"""
    
    @staticmethod
    def test_config():
        """Test Nginx configuration"""
        try:
            result = subprocess.run(
                [Config.NGINX_BIN, '-t'],
                capture_output=True,
                text=True,
                timeout=10
            )
            
            if result.returncode == 0:
                return True, "Configuration test passed"
            else:
                return False, result.stderr
        except Exception as e:
            return False, str(e)
    
    @staticmethod
    def reload():
        """Reload Nginx"""
        try:
            result = subprocess.run(
                [Config.NGINX_BIN, '-s', 'reload'],
                capture_output=True,
                text=True,
                timeout=10
            )
            
            if result.returncode == 0:
                return True, "Nginx reloaded successfully"
            else:
                return False, result.stderr
        except Exception as e:
            return False, str(e)
    
    @staticmethod
    def test_and_reload():
        """Test configuration and reload if valid"""
        success, message = NginxManager.test_config()
        
        if not success:
            return False, f"Configuration test failed: {message}"
        
        success, message = NginxManager.reload()
        return success, message

class CertbotManager:
    """Manage SSL certificates with Certbot"""
    
    @staticmethod
    def obtain_certificate(domain_name):
        """Obtain SSL certificate for domain"""
        try:
            result = subprocess.run(
                [
                    Config.CERTBOT_BIN,
                    '--nginx',
                    '-d', domain_name,
                    '--non-interactive',
                    '--agree-tos',
                    '--redirect',
                    '--hsts',
                    '--staple-ocsp',
                    '-m', 'admin@example.com'  # Change this
                ],
                capture_output=True,
                text=True,
                timeout=120
            )
            
            if result.returncode == 0:
                return True, "SSL certificate obtained successfully"
            else:
                return False, result.stderr
        except Exception as e:
            return False, str(e)